Howstheeweather it's a simple web app to get the current weather conditions in a city
carlosprietobarron/howstheweather pull request #2
Opened 2020-10-09 18:04 UTC by carlosprietobarron

This web app was created using the API facilitated by  https://openweathermap.org/api and was developed using JavaScript and bootstrap, as well as HTML and CSS.

The changes to merge are:

Module and object to handle the Request and Response to the API.

Module and object to request the current location of the user

Module to display the results of the request in the browser.

2020-10-09 21:06 UTC, uche-inyama requested changes
## Changes Required

Your project is working as it should.

However, inside your package.json add common commands like `build` and `development` inside scripts object.

* [ ] In your package.json
```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  }
```
When you are done, submit another form for a code.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2020-10-09 21:30 UTC, uche-inyama requested changes
## Changes Required.

This comment is a continuation of the first review.

* [ ] Remove commented codes.

2020-10-09 21:30 UTC, uche-inyama commented on src/index.js
> +// getDATA(cityName, getWeather.getWeaNow);
Delete commented code.

2020-10-09 21:30 UTC, uche-inyama commented on src/video.js
> +    // elem.play();
Delete commented out code.

2020-10-11 02:53 UTC, MarioDena approved these changes
Hello! Great work implementing the requested changes! 🎖️ 

Project Approved 🟢 

Cheers! 😄

2020-11-26 02:47 UTC, merged